/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hejunlin_ffmpegdecoder_NativePlayer */

#ifndef _Included_com_hejunlin_ffmpegdecoder_NativePlayer
#define _Included_com_hejunlin_ffmpegdecoder_NativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hejunlin_ffmpegdecoder_NativePlayer
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_hejunlin_ffmpegdecoder_NativePlayer_playVideo
  (JNIEn    v *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
